# Generated by Django 3.1.1 on 2020-09-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio_patentamiento', models.CharField(max_length=4)),
                ('numero_vin_o_chasis', models.CharField(max_length=50)),
                ('titular_registral', models.CharField(max_length=100)),
                ('cuit_operador', models.CharField(max_length=50)),
                ('tipo_carroceria_o_caja', models.TextField()),
                ('capacidad_total_bodega', models.IntegerField()),
                ('altura_paragolpes', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('alto', models.IntegerField()),
                ('voladizo_trasero', models.IntegerField()),
                ('primer_eje_al_segundo', models.IntegerField()),
                ('primer_eje_al_tercero', models.IntegerField()),
                ('primer_eje_al_cuarto', models.IntegerField()),
                ('primer_eje_al_centro', models.IntegerField()),
                ('peso_total', models.IntegerField()),
                ('eje_directriz', models.IntegerField()),
                ('total_sin_carga', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('tipo_lcm', models.CharField(max_length=100)),
                ('marca_lcm', models.CharField(max_length=100)),
                ('modelo_lcm', models.CharField(max_length=100)),
                ('nro_homologacion_lcm', models.CharField(max_length=50)),
                ('nro_serie_agregado_lcm', models.CharField(max_length=50)),
            ],
        ),
    ]
