# Generated by Django 3.1.1 on 2020-10-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='categoria',
            field=models.CharField(choices=[('2S', '2S'), ('1S-1D', '1S-1D')], default='2S', max_length=6),
        ),
    ]
