# Generated by Django 3.1.1 on 2020-10-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificado_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='tipo_tren',
            field=models.CharField(choices=[('2S', '2S'), ('1S-1D', '1S-1D')], default='2S', max_length=6),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='categoria',
            field=models.CharField(choices=[('N1', 'N1 hasta 3500 kg'), ('N2', 'N2 hasta 12000 kg'), ('N3', 'N2 hasta 12000 kg')], default='N1', max_length=6),
        ),
    ]
