# Generated by Django 3.1.1 on 2020-10-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20201004_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='numero_vin_o_chasis',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='primer_eje_al_centro',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='primer_eje_al_cuarto',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='primer_eje_al_segundo',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='primer_eje_al_tercero',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='tipo_carroceria_o_caja',
        ),
        migrations.AddField(
            model_name='certificado',
            name='altura_vinculacion',
            field=models.IntegerField(default=0, verbose_name='Altura de vinculación'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='distancia_primer_eje_al_centro',
            field=models.IntegerField(default=0, verbose_name='Distancia 1er eje al centro de carga'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='distancia_primer_eje_al_cuarto',
            field=models.IntegerField(default=0, verbose_name='Distancia 1er eje al 4to'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='distancia_primer_eje_al_segundo',
            field=models.IntegerField(default=0, verbose_name='Distancia 1er eje al 2do'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='distancia_primer_eje_al_tercero',
            field=models.IntegerField(default=0, verbose_name='Distancia 1er eje al 3ero'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='marca_vinculacion',
            field=models.CharField(default='', max_length=100, verbose_name='Marca de vinculación'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipo_carroceria_o_caja_carga',
            field=models.TextField(default='', verbose_name='Tipo de carrocería o caja de carga'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('CR', 'Camión rígido'), ('CT', 'Camión tractor')], default='CR', max_length=6, verbose_name='Tipo de vehículo'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='vin',
            field=models.CharField(default='', max_length=50, verbose_name='Número de chasis (VIN)'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='anio_patentamiento',
            field=models.CharField(max_length=4, verbose_name='Año de patentamiento'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='capacidad_total_bodega',
            field=models.IntegerField(verbose_name='Capacidad total bodega [m3]'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='categoria',
            field=models.CharField(choices=[('N1', 'N1 hasta 3500 kg'), ('N2', 'N2 hasta 12000 kg'), ('N3', 'N2 hasta 12000 kg')], default='N1', max_length=6, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='cuit_operador',
            field=models.CharField(max_length=50, verbose_name='CUIT operador'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='marca_lcm',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='modelo_lcm',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nro_homologacion_lcm',
            field=models.CharField(max_length=50, verbose_name='Nro. homologación'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nro_serie_agregado_lcm',
            field=models.CharField(max_length=50, verbose_name='Nro. serie agregado'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo_lcm',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
    ]
